version: '3.7'
services:
  app:
    build: .
    ports:
      - "8000:8000"
  volumes:
    - ./usr/src/app/

#"CREATE TABLE file_data( id serial PRIMARY KEY, file_name VARCHAR (50) NOT NULL, file_type VARCHAR (10), file_size INTEGER NOT NULL, md5 VARCHAR (50) NOT NULL, sha1 VARCHAR (50) NOT NULL);"